### JetBrains HTTP Client format
### See: https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html

#@host = localhost:8080
@host = lea-ingest.default.svc.cluster.local

### Single randomized security event ingestion
< {%
    import { generateEvent } from './requests_mock_helpers.js';
    const eventData = generateEvent();
    request.variables.set("random_payload", JSON.stringify(eventData, null, 2));
%}
POST http://{{host}}/events
Content-Type: application/json

{{random_payload}}

### Batch randomized security event ingestion
< {%
    import { generateEvent } from './requests_mock_helpers.js';
    const batchSize = Math.floor(Math.random() * 6) + 3;
    const batchEvents = Array.from({ length: batchSize }, () => generateEvent());
    request.variables.set("random_batch_payload", JSON.stringify({ events: batchEvents }, null, 2));
%}
POST http://{{host}}/events/batch
Content-Type: application/json

{{random_batch_payload}}
