// Code generated by "stringer -type=Severity"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SeverityInfo-0]
	_ = x[SeverityWarn-1]
	_ = x[SeverityErr-2]
	_ = x[SeverityCritical-3]
}

const _Severity_name = "SeverityInfoSeverityWarnSeverityErrSeverityCritical"

var _Severity_index = [...]uint8{0, 12, 24, 35, 51}

func (i Severity) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Severity_index)-1 {
		return "Severity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Severity_name[_Severity_index[idx]:_Severity_index[idx+1]]
}
